name: Deploy api

on:
  # on: pull_request: Runs tests/checks only. does not deploy code to Azure yet.
  push:
    branches: [main]
    paths: 
      - 'api/**' 
      - '.github/workflows/api.yml'
    workflow_dispatch:  # Allows manual trigger from GitHub UI

permissions:
  id-token: write
  contents: read

env:
  AZURE_FUNCTIONAPP_NAME: "weirdcloud-visiter-counter-api" # Name of the Azure Function App
  PYTHON_VERSION: "3.13" #ver for the python app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # this is used to run the job on a Linux machine.
    steps: 
      - name: "1. download repo code to the runner"
        uses: actions/checkout@v4 #this action checks out repo under $GITHUB_WORKSPACE, so this workflow can access it.

      - name: "2. Login Token Azure (OIDC)" 
        uses: azure/login@v2 # Use v2 for OIDC support
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: "3. Setup Python env on the runner"
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: "4. Package the api/ dir and deploy to Azure"
        uses: Azure/functions-action@v1 # this is the official GitHub Action for deploying to Azure Functions. It is a wrapper around the Azure CLI command az functionapp deployment source config-zip, which deploys a zip file to an Azure Function App.
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: "./api"
          remote-build: true

# 