name: Deploy api

on:
  # on: pull_request: Runs only tests/checks. does not deploy code to Azure yet.
  push:
    branches: [main] # only trigger this workflow on pushes to the main branch
    paths: 'api/**' # only trigger this workflow if files in the api folder are changed

permissions:
  id-token: write
  contents: read

env:
  AZURE_FUNCTIONAPP_NAME: "weirdcloud-visiter-counter-api" # Name of the Azure Function App
  PYTHON_VERSION: "3.13" #ver for the python app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # this is used to run the job on a Linux machine.
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4 #this action checks out repo under $GITHUB_WORKSPACE, so this workflow can access it.

      - name: "Login via Azure (OIDC)" 
        uses: azure/login@v2 # Use v2 for OIDC support
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: "Setup Python"
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: "Deploy to Azure Functions"
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: "."
          remote-build: true
