# azure - frontend - managed identity - blob data contributor

name: frontend deployment
on:
  push:
    branches: [main] #runs when push to main, or a PR merge. ONLY if the push includes changes to the frontend folder. 
    paths:
      - 'frontend/**'
     # - '.github/workflows/frontend.yml' 

permissions: #limit this for security
  id-token: write # allows gh to generate tk for OIDC handshake
  contents: read # Allows the action to read the code

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      # 1. Pull the code from repo
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4
      # 2. Log into Azure using OIDC
      - name: "Az CLI login"
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      # 3. Upload files to the $web container in blob
      - name: "Upload to Blob Storage"
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch \
              --account-name storageacc444resume \
              --auth-mode login \
              -d '$web' \
              -s ./frontend/ \
              --overwrite
      # Cloudflare purge step — needed because proxied = true means Cloudflare caches your static assets; without purging, visitors might see stale content after deploy until cache naturally expires:
      # - name: Purge Cloudflare Cache
      #   run: |
      #     curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CF_ZONE_ID }}/purge_cache" \
      #       -H "Authorization: Bearer ${{ secrets.CF_API_TOKEN }}" \
      #       -H "Content-Type: application/json" \
      #       --data '{"purge_everything":true}'

      #only Cloudflare's own edge cache (their PoPs / data centers worldwide). purge_everything: true tells every Cloudflare edge node to drop its cached copy, so the next request that hits any CF edge server will go back to Azure origin, fetch fresh, and re-cache.