# azure - frontend - managed identity - blob data contributor

name: OIDC frontend deployment
on:
  push:
    branches: [main] #runs when push to main
    paths:
      - 'front/**'

permissions: #limit this for security
  id-token: write # CRITICAL: This allows the OIDC handshake
  contents: read # Allows the action to read your code

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      # 1. Pull the code from your repo
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4
      # 2. Log into Azure using OIDC (No Password)
      - name: "Az CLI login"
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      # 3. Upload files to the $web container in Storage
      - name: "Sync Files to Azure"
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch \
              --account-name storageacc444resume \
              --auth-mode login \
              -d '$web' \
              -s . \
              --overwrite
